/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: m33ro (https://sketchfab.com/m33ro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-ufo-with-lights-533f12e402f2477cb438d4883144bba7
Title: Simple UFO with Lights
*/

import React, { useMemo, useRef } from "react";
import { SpotLight, useDepthBuffer, useGLTF } from "@react-three/drei";
import { AmbientLight, PointLight } from "three";
import { MovingSpot } from "./MovingSpot";

export function Ufo(props) {
  const { nodes, materials } = useGLTF("/simple_ufo_with_lights.glb");
  const depthBuffer = useDepthBuffer({ frames: 1 });

  return (
    <>
      <ambientLight intensity={3} color={"white"} />
      {/* <MovingSpot
        depthBuffer={depthBuffer}
        color="white"
        position={[0, 0.1, -6]}
      /> */}
      <group {...props} scale={0.2} dispose={null} position={[0, 0.1, -6]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.125}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
            <group
              position={[-15.626, 938.601, 28.612]}
              rotation={[-1.284, 0.134, -0.039]}
              scale={234.157}
            >
              <group
                position={[0.77, 0, -0.113]}
                rotation={[Math.PI, 0.527, -Math.PI]}
                scale={[0.074, 0.074, 0.048]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas_Material001_0_1.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas_Material001_0_2.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Det_04_-_Base_Detalhes_UFO001_0"].geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.195]}
                scale={1.02}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Det_03_-_Base_Detalhes_UFO001_0"].geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.288]}
                scale={0.926}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Det_02_-_C��pula_Detalhes_UFO001_0"].geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, 0.377]}
                scale={0.643}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Det_01_Detalhes_UFO001_0.geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.01]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Base_Form_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Base_Form_Vidro001_0.geometry}
                material={materials["Vidro.001"]}
              />
            </group>
            {/* <group
              position={[448.436, 789.431, -132.305]}
              rotation={[-2.046, 0.073, 2.451]}
              scale={234.157}
            >
              <group
                position={[0.77, 0, -0.113]}
                rotation={[Math.PI, 0.527, Math.PI]}
                scale={[0.074, 0.074, 0.048]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas001_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas001_Material001_0_1.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Janelas001_Material001_0_2.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Det_04_-_Base001_Detalhes_UFO001_0"].geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.195]}
                scale={1.02}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Det_03_-_Base001_Detalhes_UFO001_0"].geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.288]}
                scale={0.926}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes["Det_02_-_C��pula001_Detalhes_UFO001_0"].geometry
                }
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, 0.377]}
                scale={0.643}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Det_01001_Detalhes_UFO001_0.geometry}
                material={materials["Detalhes_UFO.001"]}
                position={[0, 0, -0.01]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Base_Form001_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Base_Form001_Vidro001_0.geometry}
                material={materials["Vidro.001"]}
              />
            </group> */}
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/simple_ufo_with_lights.glb");
